### ISSUE TITLE
Does Apex allow changing the User.email?

### ISSUE THREAD

**Issue by cemerson** [DouglasCAyers/sfdc-revert-user-emails-sandbox-post-copy#1]
Hey there. Sorry to ask a question unrelated to your code but this project is along the lines of what I'd like to accomplish as well - fixing all the .invalid emails after a SFDC sandbox refresh. However in my tests every time I try changing a User.email field the change is never actually saved. 

I see you're doing the same thing as me in your ([RevertUserEmailsBatchable.cls](https://github.com/douglascayers/sfdc-revert-user-emails-sandbox-post-copy/blob/13946c12aece800b4b3acadedd948e9805fc6aac/src/classes/RevertUserEmailsBatchable.cls#L22)) file. Have you seen this actually work and if so does it only work because you're calling it in the SandboxPostCopy or is there another reason it's working for you?

Thanks.

**Comment by benderguy** [comment]
Is it that you are checking the email change before the User has confirmed the change? The change can be successful but just not admin-visible until the user confirms the new email address.

**Comment by cemerson** [comment]
Thanks - yes I came to that realization as well (your reply and other posts I found since seem to confirm it). I now have an apex class I can call (via dev console) to do this - after which point the end-user gets the email to confirm and make the change permanent. Would be nice to be able to override that part via Apex but at least it's working. Thank you for the reply.
